name: Transfer Entire Project from SourceForge to GitHub

on:
  workflow_dispatch:

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install wget
      run: sudo apt-get update && sudo apt-get install -y wget

    - name: Download files from SourceForge recursively
      run: |
        mkdir -p downloaded-files
        wget -r -np -nH --cut-dirs=1 -P downloaded-files --reject "index.html*" https://sourceforge.net/projects/openwrt-passwall-build/files/releases/packages-24.10/arm_cortex-a7_neon-vfpv4/

    - name: Verify downloaded files
      run: ls -R downloaded-files

    - name: Commit and push to GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        cp -r downloaded-files/* .
        git add .
        git commit -m "Add all files from SourceForge"
        git push origin main
